import { useState } from "react";
import classes from './index.module.css'
function Secondary(a,b) {

    const [SecData] = useState({ 
        secdata: [
            {
                "id": 1,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
            {
                "id": 2,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
            {
                "id": 3,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
            {
                "id": 4,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
            {
                "id": 5,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
            {
                "id": 6,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
            {
                "id": 7,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
            {
                "id": 8,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
            {
                "id": 9,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
            {
                "id": 10,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
            {
                "id": 11,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
            {
                "id": 12,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
            {
                "id": 13,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
            {
                "id": 14,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
            {
                "id": 15,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
            {
                "id": 16,
                "value1": "大家电",
                "value2": "平板电视",
                "hyperlinks2": "#",
                "value3": "空调",
                "hyperlinks3": "#",
                "value4": "洗衣机",
                "hyperlinks4": "#",
                "value5": "DVD/电视盒子",
                "hyperlinks5": "#",
                "value6": "平板电视",
                "hyperlinks6": "#",
                "value7": "空调",
                "hyperlinks7": "#",
                "value8": "洗衣机",
                "hyperlinks8": "#",
                "value9": "DVD/电视盒子",
                "hyperlinks9": "#",
                "value10": "平板电视",
                "hyperlinks10": "#",
                "value11": "空调",
                "hyperlinks11": "#",
                "value12": "洗衣机",
                "hyperlinks12": "#",
                "value13": "DVD/电视盒子",
                "hyperlinks13": "#"
            },
        ]
    })

    return (
        <div className={classes.Secondary_menu}>
            <div className={classes.Secondary_menu_div}>
                {SecData.secdata.slice(a, b).map((sec) => (
                    <>
                        <div key={sec.id}>{sec.value1}</div>
                        <ul>
                            <li><a href={sec.hyperlinks2}>{sec.value2}</a></li>
                            <li><a href={sec.hyperlinks3}>{sec.value3}</a></li>
                            <li><a href={sec.hyperlinks4}>{sec.value4}</a></li>
                            <li><a href={sec.hyperlinks5}>{sec.value5}</a></li>
                            <li><a href={sec.hyperlinks6}>{sec.value6}</a></li>
                            <li><a href={sec.hyperlinks7}>{sec.value7}</a></li>
                            <li><a href={sec.hyperlinks8}>{sec.value7}</a></li>
                            <li><a href={sec.hyperlinks9}>{sec.value9}</a></li>
                            <li><a href={sec.hyperlinks10}>{sec.value10}</a></li>
                            <li><a href={sec.hyperlinks11}>{sec.value11}</a></li>
                            <li><a href={sec.hyperlinks12}>{sec.value12}</a></li>
                            <li><a href={sec.hyperlinks13}>{sec.value13}</a></li>
                        </ul>
                    </>
                ))}
            </div>
        </div>
    )
}

export default Secondary;